config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  devise_for :users
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :videos do
    resource :relationships,only: [:create,:destroy]
    resource :favorites,only: [:create,:destroy]
    collection do
      get 'search'
    end
  end

  root 'videos#index'

  resources :people do
    resources :tags,only: [:create]
    resources :penalties,only: [:create]
    collection do
      get 'search'
    end
  end

  resources :penalties do
    collection do
      get 'search'
    end
  end

  resources :tags do
    collection do
      get 'search'
    end
  end

  resources :places do
    collection do
      get 'search'
    end
  end

  resources :musics do
    collection do
      get 'search'
    end
  end
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :video

  validates_uniqueness_of :video_id,scope: :user_id #ユーザーは一つの投稿に一つまでいいねできる。
end

app/models/music.rb
class Music < ApplicationRecord

  has_many :music_videos,dependent: :destroy
  has_many :videos,through: :music_videos
  accepts_nested_attributes_for :music_videos
  
end

app/models/music_video.rb
class MusicVideo < ApplicationRecord

  belongs_to :music
  belongs_to :video

end

app/models/penalty.rb
class Penalty < ApplicationRecord

  has_many :penalty_videos,dependent: :destroy
  has_many :videos,through: :penalty_videos
  accepts_nested_attributes_for :penalty_videos

  belongs_to :person

end

app/models/penalty_video.rb
class PenaltyVideo < ApplicationRecord

  belongs_to :penalty
  belongs_to :video

end

app/models/person.rb
class Person < ApplicationRecord

  has_many :person_videos,dependent: :destroy
  has_many :videos,through: :person_videos
  accepts_nested_attributes_for :person_videos
  # 他のモデルを一括で更新、保存できるようにする。ここではpersonを保存するのと同時にperson_videosを更新できるようにしています。
  has_many :penalties
  has_many :tags

end

app/models/person_video.rb
class PersonVideo < ApplicationRecord
  belongs_to :person
  belongs_to :video
end

app/models/place.rb
class Place < ApplicationRecord

  has_many :place_videos,dependent: :destroy
  has_many :videos, through: :place_videos
  accepts_nested_attributes_for :place_videos
  
end

app/models/place_video.rb
class PlaceVideo < ApplicationRecord
  belongs_to :place
  belongs_to :video
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :video
  belongs_to :recommend, class_name: 'Video'

  validates :video_id, presence: true
  validates :recommend_id, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :tag_videos,dependent: :destroy
  has_many :videos,through: :tag_videos
  accepts_nested_attributes_for :tag_videos
  
  belongs_to :person
end

app/models/tag_video.rb
class TagVideo < ApplicationRecord

  belongs_to :tag
  belongs_to :video

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorites,dependent: :destroy
  has_many :videos, through: :favorites

  def already_favorited?(video)
    self.favorites.exists?(video_id: video.id)
  end

end

app/models/video.rb
class Video < ApplicationRecord

  has_many :favorites,dependent: :destroy
  has_many :users, through: :favorites
  accepts_nested_attributes_for :favorites

  has_many :person_videos,dependent: :destroy
  has_many :people, through: :person_videos

  has_many :place_videos,dependent: :destroy
  has_many :places, through: :place_videos
  
  has_many :music_videos,dependent: :destroy
  has_many :musics,through: :music_videos

  has_many :penalty_videos,dependent: :destroy
  has_many :penalties,through: :penalty_videos

  has_many :tag_videos,dependent: :destroy
  has_many :tags,through: :tag_videos

  has_many :relationships,dependent: :destroy
  has_many :recommends, through: :relationships

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  before_action :manji, except: [:index,:show,:search]


  def manji
    if user_signed_in?
      redirect_to action: :index unless current_user.id == 1
    else
      redirect_to action: :index
    end
  end

  def index
    @all_videos  = Video.all.order(updated_on:'desc')
    @videos  = @all_videos.page(params[:page]).per(40)
    @main    = @all_videos.where(kind_of: 0).page(params[:page]).per(40)
    @sub     = @all_videos.where(kind_of: 1).page(params[:page]).per(40)
    @private = @all_videos.where(kind_of: 2).page(params[:page]).per(40)
    @other   = @all_videos.where(kind_of: 3).page(params[:page]).per(40)
  end

  def search
    @search = Video.ransack(params[:q])
    @all_videos = @search.result
    @videos  = @search.result.page(params[:page]).per(40).order(updated_on: 'desc')
    @main    = @videos.where(kind_of: 0).page(params[:page]).per(40)
    @sub     = @videos.where(kind_of: 1).page(params[:page]).per(40)
    @private = @videos.where(kind_of: 2).page(params[:page]).per(40)
    @other   = @videos.where(kind_of: 3).page(params[:page]).per(40)
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)
    if @video.save
      redirect_to videos_path
    else
      render 'new'
    end
  end

  def show
    @video = Video.find(params[:id])
    @videos = Video.all.order(updated_on:'desc')
    @related = @video.recommends
    @tetsuya     = @video.people.find_by(name:'てつや')
    @shibayu     = @video.people.find_by(name:'しばゆー')
    @ryo         = @video.people.find_by(name:'りょう')
    @toshimitsu  = @video.people.find_by(name:'としみつ')
    @yumemaru    = @video.people.find_by(name:'ゆめまる')
    @mushimegane = @video.people.find_by(name:'虫眼鏡')
  end

  def edit
    @video = Video.find(params[:id])
  end

  def update
    @video = Video.find(params[:id])
    if @video.update(video_params)
      redirect_to video_path(@video)
    else
      render 'edit'
    end
  end

  def destroy
    @video = Video.find(params[:id])
    @video.destroy
    redirect_to videos_path
  end

  private
    def video_params
      params.require(:video).permit(:url,:title,:kind_of,:rate,:description,:highlight,:category,:quotes,:mvp,:editor,:updated_on,person_attributes:[:id,:name],person_ids: [],place_ids: [],penalty_ids: [],music_ids: [],tag_ids: [],recommend_ids: [])
    end

    def search_params
      params.require(:q).permit(:title_cont_or_description_or_highlight_cont_or_rate_or_updated_on_cont_or_updated_on_lteq_or_category_eq_or_mvp_eq)
    end

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/penalties_helper.rb
module PenaltiesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<div class="form_video">

  <%= form_for @video do |a| %>
  
    <div class="form-">
      <%= a.label :url , 'URL' %>
      <%= a.text_field :url,placeholder:'URLを貼り付けてください' %>
    </div>

    <div class="form-">
      <%= a.label :title , 'タイトル' %>
      <%= a.text_field :title %>
    </div>

    <div class="form-">
      <%= a.label :description ,'概要' %>
      <%= a.text_area :description %>
    </div>

    <div class="form-">
      <%= a.label :highlight ,'見所' %>
      <%= a.text_area :highlight %>
    </div>

    <div class="form-">
      <%= a.label :quotes, '名言' %>
      <%= a.text_field :quotes %>
    </div>

    <div class="form-">
      <%= a.label :rate ,'ランク' %>
      <%= a.select :rate,[["S",1],["A",2],["B",3],["C",4]],include_blank: "選択必須です" %>
    </div>

    <div class="form-">
      <%= a.label :kind_of , 'チャンネル種類' %>
      <%= a.select :kind_of,[["メインチャンネル",0],["サブチャンネル",1],["個人チャンネル",2],["その他",3]],include_blank: "選択必須です" %>
    </div>

    <div class="form-">
      <%= a.label :カテゴリー %>
      <%= a.select :category,[
        ["企画もの",0],["サブチャン",1],["コント",2],["クイズ",3],["選手権",4],["検証系",5],["対決",6],["王",7],
        ["文理対決",8],["旅行",9],["料理",10],["スポーツ",11],["ドッキリ",12],["ゲーム",13],["コラボ",14],
        ["動画アップロードチャンネル",96],["としみつ東海オンエアの",95],["虫眼鏡の放送部",94],["ブラーボりょうのボンサバドゥチャンネル",93],["ゆめまる美術館",92],["ニンマリシティへようこそ",91],
        ["晩ご飯じゃんけん",99],["いじわる",98],["十字架(サブチャン)",97]
      ],include_blank: "選択必須です" %>
    </div>

    <div class="form-collection-check">
      <%= a.label :person_ids , '出演者' %>
      <div class='form_group'>
        <%= a.collection_check_boxes(:person_ids, Person.all, :id, :name) do |person| %>
          <div class='form_check'>
              <%= person.label class: 'form-check-label' do %>
                  <%= person.check_box class: 'form-check-input' %>
                  <%= person.text %>
              <% end %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="form-">
      <%= a.label :mvp , 'マンオブザマッチ' %>
      <%= a.select :mvp,[["該当無し",0],["てつや",1],["しばゆー",2],["りょう",3],["としみつ",4],["ゆめまる",5],["虫眼鏡",6]],include_blank: "選択必須です" %>
    </div>

    <div class="form-">
      <%= a.label :編集者 %>
      <%= a.select :editor,[["不明",0],["てつや",1],["しばゆー",2],["りょう",3],["としみつ",4],["ゆめまる",5],["虫眼鏡",6]],include_blank: "選択必須です" %>
    </div>

    <div class="form-collection-check">
      <%= a.label :penalty_ids , '罰ゲーム' %>
      <div class='form_group'>
        <%= a.collection_check_boxes(:penalty_ids, Penalty.all, :id, :name) do |penalty| %>
          <div class='form_check'>
              <%= penalty.label class: 'form-check-label' do %>
                  <%= penalty.check_box class: 'form-check-input' %>
                  <%= penalty.text %>
              <% end %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="form-collection-check">
      <%= a.label :place_ids , '撮影場所' %>
      <div class='form_group'>
        <%= a.collection_check_boxes(:place_ids, Place.all, :id, :name) do |place| %>
          <div class='form_check'>
              <%= place.label class: 'form-check-label' do %>
                  <%= place.check_box class: 'form-check-input' %>
                  <%= place.text %>
              <% end %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="form-collection-check">
      <%= a.label :music_ids , 'BGM' %>
      <div class='form_group'>
        <%= a.collection_check_boxes(:music_ids, Music.all, :id, :name) do |music| %>
          <div class='form_check'>
              <%= music.label class: 'form-check-label' do %>
                  <%= music.check_box class: 'form-check-input' %>
                  <%= music.text %>
              <% end %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="form-collection-check">
      <%= a.label :tag_ids , 'ハッシュタグ' %>
      <div class='form_group'>
        <%= a.collection_check_boxes(:tag_ids, Tag.all.order(name:'asc'), :id, :name) do |tag| %>
          <div class='form_check'>
              <%= tag.label class: 'form-check-label' do %>
                  <%= tag.check_box class: 'form-check-input' %>
                  <%= tag.text %>
              <% end %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="form-collection-check">
      <%= a.label :recommend_ids , '関連動画' %>
      <div class='form_group'>
        <%= a.collection_check_boxes(:recommend_ids, Video.all.order(title:'desc'), :id, :title) do |recommend| %>
          <div class='form_check'>
              <%= recommend.label class: 'form-check-label' do %>
                  <%= recommend.check_box class: 'form-check-input' %>
                  <%= recommend.text %>
              <% end %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="form-">
      <%= a.label :投稿日 %>
      <%= a.date_select :updated_on,{start_year: 2014,end_year: 2020,use_month_numbers: true} %>
    </div>

    <div class="submit">
      <%= a.submit class: 'decorated-btn click-down' %>
    </div>
  <% end %>
  </ul>
</div> <%# form-video %>

app/views/videos/_like.html.erb
<% if user_signed_in? %>
  <% if current_user.already_favorited?(video) %>
    <%= link_to video_favorites_path(video),method: :delete, remote: true do %>
      <i class="fas fa-heart" style="color:red">
      <%= video.favorites.count %></i>
    <% end %>
  <% else %>
    <%= link_to video_favorites_path(video),method: :post, remote: true do %>
      <i class="far fa-heart">
      <%= video.favorites.count %></i>
    <% end %>
  <% end %>

<% else %>
  <%= link_to new_user_session_path do %>
   <i class="far fa-heart">
   <%= video.favorites.count %></i>
  <% end %>
<% end %>

app/views/videos/_person-color-link.html.erb
<% case person_kind %>
<% when 'てつや' , 1 %>
  <%= link_to person_path(@tetsuya) do %>
    <h3 class="tetsuya"> てつや </h3>
  <% end %>
<% when 'しばゆー',2 %>
  <%= link_to person_path(@shibayu) do %>
    <h3 class="shibayu"> しばゆー </h3>
  <% end %>
<% when 'りょう',3 %>
  <%= link_to person_path(@ryo) do %>
    <h3 class="ryo"> りょう </h3> 
  <% end %>
<% when 'としみつ' ,4%>
  <%= link_to person_path(@toshimitsu) do %>
    <h3 class="toshimitsu"> としみつ </h3>
  <% end %>
<% when 'ゆめまる',5 %>
  <%= link_to person_path(@yumemaru) do %>
    <h3 class="yumemaru"> ゆめまる </h3>
  <% end %>
<% when '虫眼鏡',6 %>
  <%= link_to person_path(@mushimegane) do %>
    <h3 class="mushimegane"> 虫眼鏡 </h3>
  <% end %>
<% when 0 %>
    <h3 class="tokai"> 不明 </h3>
<% else %>
  <%= link_to person_path(person) do %>
    <h3 class="tokai"> <%= person.name %> </h3>
  <% end %>
<% end %>

app/views/videos/_person-color.html.erb
<%# idによってクラス名を変えています。 %>

<% case person_kind %>
<% when 1 %>
  <h3 class="tetsuya"> てつや </h3>
<% when 2 %>
  <h3 class="shibayu"> しばゆー </h3>
<% when 3 %>
  <h3 class="ryo"> りょう </h3> 
<% when 4 %>
  <h3 class="toshimitsu"> としみつ </h3>
<% when 5 %>
  <h3 class="yumemaru"> ゆめまる </h3>
<% when 6 %>
  <h3 class="mushimegane"> 虫眼鏡 </h3>
<% else %>
  <h3 class="no-one"> 該当者無し </h3>
<% end %>

app/views/videos/_video-articles.html.erb
<% videos.each do |video|%>
  <%= link_to video_path(video.id) do %>
    <div class="video_article">
    
      <div class="article-image">
        <img src="https://img.youtube.com/vi/<%= video.url %>/maxresdefault.jpg">
      </div>

      <div class="article-column">
        <div class="article-title">
          <p class="article_title"><%= video.title %></p>
        </div>

        <div class="article_row">

          <div class="article-rate">
            <% case video.rate %>
              <% when 1 %>
                <h3 class="S"> S </h3>
              <% when 2 %>
                <h3 class="A"> A </h3> 
              <% when 3 %>
                <h3 class="B"> B </h3> 
              <% else %>
                <h3 class="C"> C </h3> 
            <% end %>
          </div><%# article-rate %>


          <div class="article-mvp">
            <%= render partial: "videos/person-color", locals: { person_kind: video.mvp } %>
          </div><%# article-mvp %>
          
          <div class="article-tags">
            <% video.tags.shuffle.first(4).each do |tag| %>
              <div class="article-tag btn"><h3><%= tag.name %><h3></div>
            <% end %>
          </div>

        </div><%# article_row %>


      </div><%# article-column %>

      <div class="article-date">
        <%= video.updated_on %>
        <div id="like-<%= video.id %>"> <%#いいね機能%>
          <%= render partial: "videos/like", locals: {video: video }%>
        </div>
      </div>

    </div><%# video-article %>
  <% end %>
<% end %>

app/views/videos/edit.html.erb
<h2>動画記事編集フォーム</h2>
<%= render 'form' %>

app/views/videos/index.html.erb
<%= stylesheet_link_tag "videos", :media => "all" %>

<ul class="nav nav-pills nav-fill">
  <li class="nav-item">
    <a href="#all-videos" class="nav-link active" data-toggle="tab">全動画一覧(<%= @all_videos.count %>)</a>
  </li>
  <li class="nav-item">
    <a href="#main-videos" class="nav-link" data-toggle="tab">メインチャンネル(<%= @all_videos.where(kind_of: 0).count %>)</a>
  </li>
  <li class="nav-item">
    <a href="#sub-videos" class="nav-link" data-toggle="tab">サブチャンネル(<%= @all_videos.where(kind_of: 1).count %>)</a>
  </li>
  <li class="nav-item">
    <a href="#private-videos" class="nav-link" data-toggle="tab">個人チャンネル(<%= @all_videos.where(kind_of: 2).count %>)</a>
  </li>
  <li class="nav-item">
    <a href="#deffrent-videos" class="nav-link" data-toggle="tab">その他(<%= @all_videos.where(kind_of: 3).count %>)</a>
  </li>
</ul>

<div class="tab-content">
  <div id="all-videos" class="tab-pane fade show active">
    <div class="video_articles">
      <%= render partial: "video-articles", locals: { videos: @videos }%>
    </div>
    <%= paginate @videos %>
  </div>

  <div id="main-videos" class="tab-pane fade">
    <div class="video_articles_main">
      <%= render partial: "video-articles", locals: { videos: @main }%>
    </div>
    <%= link_to_next_page @main, 'さらに見る', remote: true ,class: 'btn btn-secondary tetsuya', id: 'more_link_main' %>
  </div>

  <div id="sub-videos" class="tab-pane fade">
    <div class="video_articles_sub">
      <%= render partial: "video-articles", locals: { videos: @sub }%>
    </div>
    <%= link_to_next_page @sub, 'さらに見る', remote: true ,class: 'btn btn-secondary tetsuya', id: 'more_link_sub' %>
  </div>

  <div id="private-videos" class="tab-pane fade">
    <div class="video_articles_private">
      <%= render partial: "video-articles", locals: { videos: @private }%>
    </div>
    <%= link_to_next_page @private, 'さらに見る', remote: true ,class: 'btn btn-secondary tetsuya', id: 'more_link_private' %>
  </div>

  <div id="deffrent-videos" class="tab-pane fade">
    <div class="video_articles_other">
      <%= render partial: "video-articles", locals: { videos: @other }%>
    </div>
    <%= link_to_next_page @other, 'さらに見る', remote: true ,class: 'btn btn-secondary tetsuya', id: 'more_link_other' %>
  </div>

</div>

app/views/videos/index.js.erb
$(".video_articles_main").append("<%= escape_javascript(render partial: 'video-articles', locals: { videos: @main }) %>");
$("#more_link_main").replaceWith("<%= escape_javascript(link_to_next_page(@main, 'さらに見る', remote: true ,class: 'btn btn-secondary tetsuya', id: 'more_link_main')) %>");

$(".video_articles_sub").append("<%= escape_javascript(render partial: 'video-articles', locals: { videos: @sub }) %>");
$("#more_link_sub").replaceWith("<%= escape_javascript(link_to_next_page(@sub, 'さらに見る', remote: true ,class: 'btn btn-secondary tetsuya', id: 'more_link_sub')) %>");

$(".video_articles_private").append("<%= escape_javascript(render partial: 'video-articles', locals: { videos: @private }) %>");
$("#more_link_private").replaceWith("<%= escape_javascript(link_to_next_page(@private, 'さらに見る', remote: true ,class: 'btn btn-secondary tetsuya', id: 'more_link_private')) %>");

$(".video_articles_other").append("<%= escape_javascript(render partial: 'video-articles', locals: { videos: @other }) %>");
$("#more_link_other").replaceWith("<%= escape_javascript(link_to_next_page(@other, 'さらに見る', remote: true ,class: 'btn btn-secondary tetsuya', id: 'more_link_other')) %>");

app/views/videos/new.html.erb
<h2>動画記事作成フォーム</h2>
<%= render 'form' %>

app/views/videos/show.html.erb
<%= stylesheet_link_tag "videos", :media => "all" %>

<div class="all-contents">

  <div class="video_box">
    <div class="video-youtube">
      <iframe width="100%" height="100%" src="https://www.youtube.com/embed/<%= @video.url %>?autoplay=1&loop=1&playlist=<%= @video.url %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>

    <div class="video_title">
      <h3> <%= @video.title %> </h3>
    </div>

    <div class="video_date">
      <h2><%= @video.updated_on %> に公開済み </h2>

    <%# 自分がログインしているときのみ表示  %>
    <% if user_signed_in?  && current_user.id == 1 %>
        <%= link_to '編集',edit_video_path(@video) %>
        <%= link_to '削除',video_path(@video) ,
        method: :delete,
        data: {confirm: '本当に削除しますか？'}
        %>
    <% end %>
    </div>

    <div id="like-<%= @video.id %>"> <%#いいね機能%>
      <%= render partial: "videos/like", locals: {video: @video }%>
    </div>

    <table border="1px" style="border-collapse: collapse; border-color: rgb(238, 232, 232)">


      <tr class="video-title">
        <th> タイトル </th>
        <th>   
          <p> <%= @video.title %> </p>
        </th>
      </tr>

      <tr class="video-description">
        <th> 概要 </th>
        <th>   
          <p> <%=safe_join(@video.description.split("\n"),tag(:br))%> </p>
        </th>
      </tr>

      <tr class="video-highlight">
        <th> 見所 </th>
        <th>   
          <p> <%=safe_join(@video.highlight.split("\n"),tag(:br))%> </p>
        </th>
      </tr>

      <tr class="video-quotes">
        <th> 名言 </th>
        <th>   
          <p> <%= @video.quotes %> </p>
        </th>
      </tr>

      <tr>
        <th> ランク </th>
        <th>
          <div class="video-rate">
            <% case @video.rate %>
              <% when 1 %>
                <h3 class="S"> S </h3>
              <% when 2 %>
                <h3 class="A"> A </h3> 
              <% when 3 %>
                <h3 class="B"> B </h3> 
              <% else %>
                <h3 class="C"> C </h3> 
            <% end %>
          </div>
        </th>
      </tr>

      <tr class="video_kind_of">
        <th> チャンネル種類 </th>
        <th>
          <div class="channel">
            <% case @video.kind_of %>
              <% when 0 %>
                <h3> メインチャンネル </h3>
              <% when 1 %>
                <h3> 東海オンエアの控え室 </h3> 
              <% when 2 %>
                <h3> 個人チャンネル </h3> 
              <% else %>
                <h3> その他のチャンネル </h3> 
            <% end %>
          </div>
        </th>
      </tr>

      <tr>
        <th> カテゴリー </th>
        <th>   
          <div class="video-category">
            <% case @video.category %>
              <% when 0 %>
                <h3> 企画もの </h3>
              <% when 1 %>
                <h3> サブチャン </h3>
              <% when 2 %>
                <h3> コント </h3> 
              <% when 3 %>
                <h3> クイズ </h3>
              <% when 4 %>
                <h3> 選手権 </h3>
              <% when 5 %>
                <h3> 検証系 </h3>
              <% when 6 %>
                <h3> 対決 </h3>
              <% when 7 %>
                <h3> 王 </h3>
              <% when 8 %>
                <h3> 王 </h3>
              <% when 9 %>
                <h3> 旅行 </h3>
              <% when 10 %>
                <h3> 料理 </h3>
              <% when 11 %>
                <h3> スポーツ </h3>
              <% when 12 %>
                <h3> ドッキリ </h3>
              <% when 13 %>
                <h3> ゲーム </h3>
              <% when 14 %>
                <h3> コラボ </h3>
              <% when 91 %>
                <h3> ニンマリシティへようこそ </h3>
              <% when 92 %>
                <h3> ゆめまる美術館 </h3>
              <% when 93 %>
                <h3> ブラーボりょうのボンサバドゥチャンネル </h3>
              <% when 94 %>
                <h3> 虫眼鏡の放送部 </h3>
              <% when 95 %>
                <h3> としみつ東海オンエアの </h3>
              <% when 96 %>
                <h3> 動画アップロードチャンネル </h3>
              <% when 99 %>
                <h3> ご飯じゃんけん </h3>
              <% when 98 %>
                <h3> いじわる </h3>
              <% when 97 %>
                <h3> 十字架(サブチャン) </h3>
              <% else %>
                <h3> その他 </h3> 
            <% end %>
          </div>
        </th>
      </tr>

      <tr>
        <th> 登場メンバー </th>
        <th>
          <div class="video-people">
            <% @video.people.each do |person| %>
              <div class="video-person-cast">
                <%= render partial: "person-color-link", locals: { person_kind: person.name,person: person } %>
              </div>
            <% end %>
          </div>
        </th>
      </tr>

      <tr class="video-mvp">
        <th> マンオブザマッチ </th>
        <th>
          <div class="video-person-mvp">
            <%= render partial: "person-color-link", locals: { person_kind: @video.mvp } %>
          </div>
        </th>
      </tr>

      <tr>
        <th> 編集者 </th>
        <th>
          <div class="video-person-editor">
            <%= render partial: "person-color-link", locals: { person_kind: @video.editor } %>
          </div>
        </th>
      </tr>


      <tr>
        <th> 撮影場所 </th>
        <th>
          <div class="places">
            <% @video.places.each do |place| %>
              <%= link_to place_path(place.id) do %>
                <div class="btn btn-danger">
                  <%= place.name %>
                </div>
              <% end %>
            <% end %>
          </div>
        </th>
      </tr>

      <tr>
        <th> BGM </th>
        <th>
          <div class="musics">
            <% @video.musics.each do |music| %>
              <div class="btn btn-success">
                <%= link_to music.name ,music_path(music.id)%>
              </div>
            <% end %>
          </div>
        </th>
      </tr>

      <tr>
        <th> 罰ゲーム </th>
        <th>
          <div class="penalties">
              <%= render partial: "penalties/penalty-color", locals: { penalties: @video.penalties }%>
          </div> <%# video-tags %>
        </th>
      </tr>

      <tr>
        <th> ハッシュタグ </th>
        <th> 
          <div class="tags">
              <%= render partial: "tags/tag-color", locals: { tags: @video.tags }%>
          </div> <%# video-tags %>
        </th>
      </tr>

      <tr class="video-updated_on">
        <th> アップロード日 </th>
        <th>   
          <%= @video.updated_on %> 
        </th>
      </tr>

    </table>

  </div>

  <div class="related-videos">
    <%= render partial: "video-articles", locals: { videos: @related }%>
    <%= render partial: "video-articles", locals: { videos: Video.all.sample(6) }%>
  </div>