config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  devise_for :users
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :videos do
    resource :relationships,only: [:create,:destroy]
    resource :favorites,only: [:create,:destroy]
    collection do
      get 'search'
    end
  end

  root 'videos#index'

  resources :people do
    resources :tags,only: [:create]
    resources :penalties,only: [:create]
    collection do
      get 'search'
    end
  end

  resources :penalties do
    collection do
      get 'search'
    end
  end

  resources :tags do
    collection do
      get 'search'
    end
  end

  resources :places do
    collection do
      get 'search'
    end
  end

  resources :musics do
    collection do
      get 'search'
    end
  end
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :video

  validates_uniqueness_of :video_id,scope: :user_id #ユーザーは一つの投稿に一つまでいいねできる。
end

app/models/music.rb
class Music < ApplicationRecord

  has_many :music_videos,dependent: :destroy
  has_many :videos,through: :music_videos
  accepts_nested_attributes_for :music_videos
  
end

app/models/music_video.rb
class MusicVideo < ApplicationRecord

  belongs_to :music
  belongs_to :video

end

app/models/penalty.rb
class Penalty < ApplicationRecord

  has_many :penalty_videos,dependent: :destroy
  has_many :videos,through: :penalty_videos
  accepts_nested_attributes_for :penalty_videos

  belongs_to :person

end

app/models/penalty_video.rb
class PenaltyVideo < ApplicationRecord

  belongs_to :penalty
  belongs_to :video

end

app/models/person.rb
class Person < ApplicationRecord

  has_many :person_videos,dependent: :destroy
  has_many :videos,through: :person_videos
  accepts_nested_attributes_for :person_videos
  # 他のモデルを一括で更新、保存できるようにする。ここではpersonを保存するのと同時にperson_videosを更新できるようにしています。
  has_many :penalties
  has_many :tags

end

app/models/person_video.rb
class PersonVideo < ApplicationRecord
  belongs_to :person
  belongs_to :video
end

app/models/place.rb
class Place < ApplicationRecord

  has_many :place_videos,dependent: :destroy
  has_many :videos, through: :place_videos
  accepts_nested_attributes_for :place_videos
  
end

app/models/place_video.rb
class PlaceVideo < ApplicationRecord
  belongs_to :place
  belongs_to :video
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :video
  belongs_to :recommend, class_name: 'Video'

  validates :video_id, presence: true
  validates :recommend_id, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :tag_videos,dependent: :destroy
  has_many :videos,through: :tag_videos
  accepts_nested_attributes_for :tag_videos
  
  belongs_to :person
end

app/models/tag_video.rb
class TagVideo < ApplicationRecord

  belongs_to :tag
  belongs_to :video

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorites,dependent: :destroy
  has_many :videos, through: :favorites

  def already_favorited?(video)
    self.favorites.exists?(video_id: video.id)
  end

end

app/models/video.rb
class Video < ApplicationRecord

  has_many :favorites,dependent: :destroy
  has_many :users, through: :favorites
  accepts_nested_attributes_for :favorites

  has_many :person_videos,dependent: :destroy
  has_many :people, through: :person_videos

  has_many :place_videos,dependent: :destroy
  has_many :places, through: :place_videos
  
  has_many :music_videos,dependent: :destroy
  has_many :musics,through: :music_videos

  has_many :penalty_videos,dependent: :destroy
  has_many :penalties,through: :penalty_videos

  has_many :tag_videos,dependent: :destroy
  has_many :tags,through: :tag_videos

  has_many :relationships,dependent: :destroy
  has_many :recommends, through: :relationships

end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :manji, except: [:index,:show]

  def manji
    if user_signed_in?
      redirect_to action: :index unless current_user.id == 1
    else
      redirect_to action: :index
    end
  end
  
  def index
    @searches = Music.ransack(params[:q])
    # @musics = Music.all.order(created_at:'asc')
    @musics = Music.joins(:music_videos).group(:music_id).order('count(video_id) desc')
  end

  def search
    @searches = Music.ransack(params[:q])
    @musics = @searches.result.order(created_at: 'desc')
    render 'index'
  end

  def show
    @music = Music.find(params[:id])
    @musics = Music.all.sample(10)
  end

  def new
    @music = Music.new
  end

  def create
    @music = Music.new(music_params)
      if @music.save
        redirect_to musics_path
      else
        render 'new'
      end
  end

  def edit
    @music = Music.find(params[:id])
  end

  def update
    @music = Music.find(params[:id])
    if @music.update(music_params)
      redirect_to musics_path
    else
      render 'edit'
    end
  end

  def destroy
    @music = Music.find(params[:id])
    @music.destroy
    redirect_to musics_path
  end

  private
  def music_params
    params.require(:music).permit(:name,:description,:url)
  end

  def search_params
    params.require(:q).permit(:name_cont_or_description_cont)
  end

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/penalties_helper.rb
module PenaltiesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/musics/edit.html.erb
<h2>BGM編集フォーム</h2>
<div class="bgm_form">
<%= form_for @music,url: music_path(@music) do |a| %>
  <ul>

    <li>
      <%= a.label :name ,'BGM名' %>
      <%= a.text_field :name,placeholder:'BGM名を入力してください' %>
    </li>

    <li>
      <%= a.label :description ,'概要' %>
      <%= a.text_area :description,placeholder:'概要を入力してください' %>
    </li>

    <li>
        <%= a.label :url , 'URL' %>
        <%= a.text_field :url,placeholder:'URLを貼り付けてください' %>
    </li>

    <li>
      <%= a.submit %>
    </li>

  </ul>
<% end %>
</div>

app/views/musics/index.html.erb
<%= stylesheet_link_tag "musics", :media => "all" %>

<h1>BGMリスト</h1>

<%# 自分がログインしているときのみ表示  %>
<% if user_signed_in?  && current_user.id == 1 %>
  <h2> <%= link_to 'BGM作成' ,new_music_path if current_user.id == 1 %> </h2>
<% end %>


<%= search_form_for @searches,html: { class: "form-inline" }, url: search_musics_path do |f| %>
 <%= f.label :name_or_description, 'ハッシュタグ検索' %>
 <%= f.search_field :name_or_description_cont %>
 <%= f.submit '検索' %>
<% end %>

<% @musics.each do |music|%>
  <div class="btn btn-success">
    <%= link_to music_path(music.id) do %>
      <%= music.name %>
      (<%= music.videos.count %>)
    <% end %>
  </div>
<% end %>

app/views/musics/new.html.erb
<h1>BGM作成フォーム</h1>

<%= form_for @music,url: musics_path do |f| %>
<ul>

  <li>
    <%= f.label :name ,'曲名' %>
    <%= f.text_field :name,placeholder:'曲名を入力してください' %>
  </li>

  <li>
    <%= f.label :description ,'概要' %>
    <%= f.text_area :description,placeholder:'概要を入力してください' %>
  </li>

  <li>
      <%= f.label :url , 'URL' %>
      <%= f.text_field :url,placeholder:'URLを貼り付けてください' %>
  </li>

  <li>
    <%= f.submit %>
  </li>

</ul>
<% end %>

app/views/musics/show.html.erb
<%= stylesheet_link_tag "musics", :media => "all" %>

<p><%= link_to 'BGM一覧に戻る',musics_path %></p>


<div class="article-image">
  <iframe src="https://www.youtube.com/embed/<%= @music.url %>?autoplay=1&loop=1&playlist=<%= @music.url %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

<div class="music-show">
  <table class="table table-borderless">
    <tr> 
      <th>BGM名</th> 
      <th><%= @music.name %> </th> 
    </tr>
    <tr> 
      <th>概要</th> 
      <th> <%=safe_join(@music.description.split("\n"),tag(:br))%> </th>
    </tr>
</table>
</div>

<div class="recommend-bgm">
  <h2>おすすめBGM</h2>
  <% @musics.each do |music|%>
    <div class="btn btn-success">
      <%= link_to music_path(music.id) do %>
        <%= music.name %>
        (<%= music.videos.count %>)
      <% end %>
    </div>
  <% end %>
</div>




<% if user_signed_in?  && current_user.id == 1 %>
  <%= link_to '編集',edit_music_path(@music) %>
  <%= link_to '削除',music_path(@music),
    method: :delete,
    data: {confirm: '本当に削除しますか？'}
  %>
<% end %>

<h2><%= @music.name %> が使われている動画リスト </h2>
<div class="video_articles">
  <%= render partial: "videos/video-articles", locals: { videos: @music.videos } %>
</div>

<%= @music.id %>