config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  devise_for :users
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :videos do
    resource :relationships,only: [:create,:destroy]
    resource :favorites,only: [:create,:destroy]
    collection do
      get 'search'
    end
  end

  root 'videos#index'

  resources :people do
    resources :tags,only: [:create]
    resources :penalties,only: [:create]
    collection do
      get 'search'
    end
  end

  resources :penalties do
    collection do
      get 'search'
    end
  end

  resources :tags do
    collection do
      get 'search'
    end
  end

  resources :places do
    collection do
      get 'search'
    end
  end

  resources :musics do
    collection do
      get 'search'
    end
  end
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :video

  validates_uniqueness_of :video_id,scope: :user_id #ユーザーは一つの投稿に一つまでいいねできる。
end

app/models/music.rb
class Music < ApplicationRecord

  has_many :music_videos,dependent: :destroy
  has_many :videos,through: :music_videos
  accepts_nested_attributes_for :music_videos
  
end

app/models/music_video.rb
class MusicVideo < ApplicationRecord

  belongs_to :music
  belongs_to :video

end

app/models/penalty.rb
class Penalty < ApplicationRecord

  has_many :penalty_videos,dependent: :destroy
  has_many :videos,through: :penalty_videos
  accepts_nested_attributes_for :penalty_videos

  belongs_to :person

end

app/models/penalty_video.rb
class PenaltyVideo < ApplicationRecord

  belongs_to :penalty
  belongs_to :video

end

app/models/person.rb
class Person < ApplicationRecord

  has_many :person_videos,dependent: :destroy
  has_many :videos,through: :person_videos
  accepts_nested_attributes_for :person_videos
  # 他のモデルを一括で更新、保存できるようにする。ここではpersonを保存するのと同時にperson_videosを更新できるようにしています。
  has_many :penalties
  has_many :tags

end

app/models/person_video.rb
class PersonVideo < ApplicationRecord
  belongs_to :person
  belongs_to :video
end

app/models/place.rb
class Place < ApplicationRecord

  has_many :place_videos,dependent: :destroy
  has_many :videos, through: :place_videos
  accepts_nested_attributes_for :place_videos
  
end

app/models/place_video.rb
class PlaceVideo < ApplicationRecord
  belongs_to :place
  belongs_to :video
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :video
  belongs_to :recommend, class_name: 'Video'

  validates :video_id, presence: true
  validates :recommend_id, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :tag_videos,dependent: :destroy
  has_many :videos,through: :tag_videos
  accepts_nested_attributes_for :tag_videos
  
  belongs_to :person
end

app/models/tag_video.rb
class TagVideo < ApplicationRecord

  belongs_to :tag
  belongs_to :video

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorites,dependent: :destroy
  has_many :videos, through: :favorites

  def already_favorited?(video)
    self.favorites.exists?(video_id: video.id)
  end

end

app/models/video.rb
class Video < ApplicationRecord

  has_many :favorites,dependent: :destroy
  has_many :users, through: :favorites
  accepts_nested_attributes_for :favorites

  has_many :person_videos,dependent: :destroy
  has_many :people, through: :person_videos

  has_many :place_videos,dependent: :destroy
  has_many :places, through: :place_videos
  
  has_many :music_videos,dependent: :destroy
  has_many :musics,through: :music_videos

  has_many :penalty_videos,dependent: :destroy
  has_many :penalties,through: :penalty_videos

  has_many :tag_videos,dependent: :destroy
  has_many :tags,through: :tag_videos

  has_many :relationships,dependent: :destroy
  has_many :recommends, through: :relationships

end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>かんた東海オンエア伝導大使の</title>
    <%= analytics_init if Rails.env.production? %> <%# グーグルアナリティクス用 %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all','data-turbolinks-eval': 'false'%>
    <%= javascript_pack_tag 'application','data-turbolinks-eval': 'false' %>
  </head>

  <body>

    <%# <div class="navbar"> %>
    <nav class="navbar navbar-light bg-white fixed-top">
      <div>
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <%= link_to image_tag('tokaidb-logo.jpg',size: '400x60'),videos_path %>
      </div>

    <%# 自分がログインしているときのみ表示  %>
    <% if user_signed_in?  && current_user.id == 1 %>
      <%= link_to '記事作成' ,new_video_path  %>
    <% end %>

      <div class="nav-serch">
        <%= search_form_for @search,html: { class: "form-inline" }, url: search_videos_path do |f| %>
          <%#= f.label :title_or_description_or_highlight, 'キーワード' %>
          <%= f.search_field :title_or_description_or_highlight_cont %>
          <%= f.submit '検索' %>
        <% end %>

        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo">詳細検索</button>

        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">詳細検索</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <%= search_form_for @search,html: { class: "form-inline" }, url: search_videos_path do |f| %>
                <div class="modal-body">

                  <div class="form_">
                    <%= f.label :sorts ,'並び替え' %>
                    <%= f.select :sorts, { '新しい順': 'updated_on desc', '古い順': 'updated_on asc','作成順': 'created_at desc'} , { selected: params[:q][:sorts] } %>
                  </div>

                  <div class="form_">
                    <%= f.label :rate ,'ランク' %>
                    <%= f.select :rate_eq,[["S",1],["A",2],["B",3],["C",4]],include_blank: true %>
                  </div>

                  <div class="form_">
                    <%= f.label :カテゴリー %>
                    <%= f.select :category_eq,[
                      ["企画もの",0],["サブチャン",1],["コント",2],["クイズ",3],["選手権",4],["検証系",5],["対決",6],["王",7],
                      ["文理対決",8],["旅行",9],["料理",10],["スポーツ",11],["ドッキリ",12],["ゲーム",13],["コラボ",14],
                      ["動画アップロードチャンネル",96],["としみつ東海オンエアの",95],["虫眼鏡の放送部",94],["ブラーボりょうのボンサバドゥチャンネル",93],["ゆめまる美術館",92],["ニンマリシティへようこそ",91],
                      ["晩ご飯じゃんけん",99],["いじわる",98],["十字架(サブチャン)",97]
                    ],include_blank: true %>
                  </div>

                  <div class="form_">
                    <%= f.label :mvp , 'マンオブザマッチ' %>
                    <%= f.select :mvp_eq,[["該当無し",0],["てつや",1],["しばゆー",2],["りょう",3],["としみつ",4],["ゆめまる",5],["虫眼鏡",6]],include_blank: true %>
                  </div>

                  <div class="form-date">
                    <%= f.label :updated_on, 'アップデート日'%>
                    <%= f.date_select :updated_on_gteq,{start_year: 2013,end_year: 2020,include_blank: true} %>
                    <%= f.label :updated_on_cont, 'から' %>
                    <%= f.date_select :updated_on_lteq,{start_year: 2013,end_year: 2020,include_blank: true} %>
                  </div>

                  <div class="form_">
                    <%= f.label :title_or_description_or_highlight, 'キーワード' %>
                    <%= f.search_field :title_or_description_or_highlight_cont %>
                  </div>
                </div>

                <div class="modal-footer">
                  <%= f.submit '検索' %>
                </div>
              <% end %>
            </div>
          </div>
        </div>

      </div>

      <% if user_signed_in? %>
        <div class="user_btn">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
        </div>
      <% else %>
        <div class="user_btn">
          <div class="not-user">
            <%= link_to "ログイン", new_user_session_path, class: 'post' %>
            /
            <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
          </div>
         </div>
      <% end %>

        
      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item">
          <li class="nav-item">
            <% if user_signed_in? %>
              <li>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete,class: 'nav-link' %>
              </li>
              <li>
                <%= link_to "いいねした動画",user_path(current_user.id), {class: "nav-link"} %>
              </li>
            <% else %>
                <li>
                  <%= link_to "ログイン", new_user_session_path, class: 'nav-link' %>
                </li>
                <li>
                  <%= link_to "新規登録", new_user_registration_path, class: 'nav-link' %>
                </li>
            <% end %>
          <li class="nav-item">
            <%= link_to "登場人物",people_path, {class: "nav-link"} %>
          </li>
          <li class="nav-item">
            <%= link_to "罰ゲーム(十字架)",penalties_path,{class: "nav-link"} %>
          </li>
          <li class="nav-item">
            <%= link_to "撮影場所",places_path ,{class: "nav-link"}%>
          </li>
          <li class="nav-item">
            <%= link_to "BGM",musics_path,{class: "nav-link"} %>
          </li>
          <li class="nav-item">
            <%= link_to "ハッシュタグ",tags_path,{class: "nav-link"} %>
          </li>

        </ul>
      </div>
    </nav>

    <%# ↓deviseのフラッシュメッセージを表示するもの %>
    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <%# ↑devise用の記述 %>

    <div class="main-contents">
      <div class="yield"><%= yield %></div>
    </div>

  </body>
</html>